---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-db-secrets
              key: db_sa_password
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
          - name: sql-persistent-storage
            mountPath: /var/opt/mssql/data
      volumes:
        - name: sql-persistent-storage
          persistentVolumeClaim:
            claimName: sql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mssql
  selector:
    app: db
  type: NodePort