---
apiVersion: v1
kind: Secret
metadata:
  name: sql-db-secrets
type: Opaque
data:
  db_sa_password: Um9vdCMxMjM0NTY=

# password should be 64-base encoded
# go to terminal and use cmd
# echo -n 'Root#123456' | base64
# apply the secret before db-deployment wthy cmd
# kubectl apply -f sql_secrets